Metrics/AbcSize:
  Max: 18

Metrics/LineLength:
  Max: 90

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/Documentation:
  Enabled: false

Style/IndentHash:
  EnforcedStyle: consistent

Style/MultilineBlockChain:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  '{}'
    '%i': '[]'
    '%q': '{}'
    '%Q': '{}'
    '%r': '{}'
    '%s': '{}'
    '%w': '[]'
    '%W': '[]'
    '%x': '{}'

Style/PredicateName:
  NamePrefixBlacklist:
    - is_

Style/RegexpLiteral:
  EnforcedStyle: mixed

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
