Encoding:
  Enabled: false
Documentation:
  Enabled: false
Style/MultilineOperationIndentation:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  []
    '%i': []
    '%q': []
    '%Q': []
    '%r': '{}'
    '%s': []
    '%w': []
    '%W': []
    '%x': []
